#baseURL = "http://davidtrumbell.com/"
baseURL = "https://djtrumbe.github.io/"
languageCode = "en-us"
title = "David Trumbell"
theme = "gohugo-theme-ananke"
staticDir = ["static"]

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 12
disqusShortname = "davidtrumbell"

[params]
  description = "Anything I can think of"
  featured_image = "/images/header_image.jp2"
  recent_posts_number = 6
  twitter = "https://twitter.com/davidtrumbell"
